image: alpine/edge
packages:
  - hugo
  - rsync
sources:
  - https://github.com/Schnouki/schnouki.net
environment:
  DEPLOY_HOST: schnouki@schnouki.net
  DEPLOY_PATH: /
secrets:
  - cbdbfd58-46d3-4abb-abe1-3eed67fe6ec0
tasks:
  - build_and_deploy: |
      cd schnouki.net
      make build upload
