baseURL = "https://schnouki.net/"
title = "/dev/schnouki"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

ignoreFiles = ["/\\.#.+", "~$"]

[params.info]
description = "A blog about Emacs, Linux, and other things I care about."
title404 = "There's nothing here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/schnouki.css"]
customJS = [] # "js/schnouki.js"]
gopher = "/img/gopher.png" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Thomas Jost"
startYear = "2009"
suffix = """— licensed under a <a rel="license" href="//creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>."""
logo = "/android-chrome-512x512.png"

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
archiveDateFormat = "02 Jan"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
showLastMod = true
taxonomyCloudShuffle = false
accentColor = "#7b7bde"
hideMainMenu = true

[params.sidebar]
enable = true

[params.widgets]
homepage = ["home_intro","recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"] # "search"
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "Schnouki" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = "schnouki+blog@schnouki.net"
facebook = ""
github = "Schnouki"
gitlab = "Schnouki"
instagram = ""
linkedin = ""
twitter = "Schnouki"
telegram = ""
google_scholar = ""
youtube = ""

[params.comments]
enable = true

[params.comments.isso]
enable = true
scriptSrc = "/isso/js/embed.min.js"
dataAttrs = 'data-isso="/isso/" data-isso-require-author="true" data-isso-require-email="true" data-isso-gravatar="true" data-isso-avatar="false" data-isso-feed="true" data-isso-reply-notifications="true"'

[params.search]
client = "fuse" # algolia / fuse / lunr

[taxonomies]
#author = "authors"
category = "categories"
#series = "series"
tag = "tags"

[permalinks]
post = "/post/:year/:slug/"
page = "/:slug/"

[[menu.main]]
name = "Categories"
weight = 100
identifier = "categories"
url = "/categories/"

[[menu.main]]
name = "Tags"
weight = 110
identifier = "tags"
url = "/tags/"

[[menu.main]]
name = "Archives"
weight = 120
identifier = "archives"
url = "/post/"

[[menu.home_intro]]
identifier = "spop"
name = "spop"
title = "A Spotify client running as a daemon, similar to mpd."
url = "https://github.com/Schnouki/spop"
weight = 10

[[menu.home_intro]]
identifier = "dotfiles"
name = "dotfiles"
title = "Many of my configuration files."
url = "https://github.com/Schnouki/dotfiles"
weight = 20

[[menu.home_intro]]
identifier = "git-annex-remote-hubic"
name = "git-annex-remote-hubic"
title = "A git-annex special remote for hubiC"
url = "https://github.com/Schnouki/git-annex-remote-hubic"
weight = 30

[[menu.home_intro]]
identifier = "stibidik"
name = "STIBIDIK"
title = "My company 😉"
url = "https://www.stibidik.fr/"
weight = 40

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language

[languages.en]
lang = "en"
languageName = "English"
weight = 1
