# Source: https://gist.github.com/nitely/8832362

# Tested on Markdown 2.3.1
#
# Copyright (c) 2014, Esteban Castro Borsani
# The MIT License (MIT)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import os, os.path
import re

from markdown.extensions import Extension
from markdown.preprocessors import Preprocessor

# Grab the emojis (+800) here: https://github.com/arvida/emoji-cheat-sheet.com
# This **crazy long** list was generated by walking through the emojis.png
EMOJIS_URL = "/emojis/"
EMOJIS_PATH = "content/emojis"
EMOJIS_SET = {os.path.splitext(fn)[0] for fn in os.listdir(EMOJIS_PATH)}

EMOJI_RE = re.compile(r":([a-z0-9\+\-_]+):", flags=re.UNICODE)

class EmojifyExtension(Extension):
    def extendMarkdown(self, md, md_globals):
        md.registerExtension(self)
        md.preprocessors.add('emojify', EmojifyPreprocessor(md), '_end')

class EmojifyPreprocessor(Preprocessor):
    def run(self, lines):
        new_lines = []

        def emojify(match):
            emoji = match.group(1)
            if emoji not in EMOJIS_SET:
                return match.group(0)

            url = EMOJIS_URL + emoji + ".png"
            return u'![%(emoji)s]({static|"%(url)s"})' % {'emoji': emoji, 'url': url}

        for line in lines:
            if line.strip():
                line = EMOJI_RE.sub(emojify, line)
            new_lines.append(line)

        return new_lines


def makeExtension(configs=None):
    return EmojifyExtension(configs=configs)
